site_name: Dokumentation für Mission Control Paramedic (inoffiziell)
theme:
  name: material
  language: de
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: indigo

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox

nav:
  - Startseite: index.md
  - Einführung:
      - Erste Schritte: getting_started.md
      - Installation: installation.md
      - Fortgeschrittene: advanced.md
  - Tools: tools.md
  - FAQ: faq.md
  - Technische Dokumentation: file_formats.md